def media_type(message):
    if message:
        if message.photo:
            return "Photo"
        if message.audio:
            return "Audio"
        if message.voice:
            return "Voice"
        if message.video_note:
            return "Round Video"
        if message.gif:
            return "Gif"
        if message.sticker:
            return "Sticker"
        if message.video:
            return "Video"
        if message.document:
            return "Document"
    return None
